// EXPRESS RELATED STUFF
const DEFAULT_HTTP_PORT: number = 5000;
const DEFAULT_SECRET_KEY: string = "capybara";

// MQTT RELATED STUFF

const DEFAULT_MQTT_PROTOCOL = 'mqtt'
const DEFAULT_MQTT_HOST = 'broker.emqx.io'
const DEFAULT_MQTT_PORT = '1883'

export {DEFAULT_SECRET_KEY, DEFAULT_HTTP_PORT, DEFAULT_MQTT_PROTOCOL, DEFAULT_MQTT_HOST, DEFAULT_MQTT_PORT}