// EXPRESS RELATED STUFF
const DEFAULT_HTTP_PORT: string = "3000";
const DEFAULT_SECRET_KEY: string = "capybara";

// MQTT RELATED STUFF

const DEFAULT_MQTT_PROTOCOL: string = "mqtt"
const DEFAULT_MQTT_HOST: string = "broker.emqx.io"
const DEFAULT_MQTT_PORT: string = "1883"

// DATABASE RELATED STUFF

const DEFAULT_DB_HOST: string = "127.0.0.1"
const DEFAULT_DB_PORT: string = "3306"
const DEFAULT_DB_DRIVER: string = "mariadb"
const DEFAULT_DB_USER: string = "root"
const DEFAULT_DB_PASS: string = "SecurePassword"
const DEFAULT_DB_NAME: string = "DatabaseName"

// EXPORTS

export { DEFAULT_SECRET_KEY, DEFAULT_HTTP_PORT, DEFAULT_MQTT_PROTOCOL, DEFAULT_MQTT_HOST, DEFAULT_MQTT_PORT, DEFAULT_DB_HOST, DEFAULT_DB_PORT, DEFAULT_DB_USER, DEFAULT_DB_PASS, DEFAULT_DB_NAME, DEFAULT_DB_DRIVER}